// Mock data fallback provider for GitHub Pages / Static Hosting when backend is not deployed
export const MOCK_USERS = [
  {
    id: 'usr-admin-01',
    email: 'admin@microlims.lab',
    name: 'Dr. Sarah Chen',
    title: 'Laboratory Director',
    roles: ['ADMIN', 'MICROBIOLOGIST', 'TECHNICIAN', 'REVIEWER', 'VIEWER'],
  },
  {
    id: 'usr-tech-01',
    email: 'tech@microlims.lab',
    name: 'Alex Rivera',
    title: 'Medical Lab Technician',
    roles: ['TECHNICIAN', 'VIEWER'],
  },
  {
    id: 'usr-micro-01',
    email: 'micro@microlims.lab',
    name: 'Dr. Marcus Vance',
    title: 'Senior Microbiologist',
    roles: ['MICROBIOLOGIST', 'TECHNICIAN', 'VIEWER'],
  },
  {
    id: 'usr-rev-01',
    email: 'reviewer@microlims.lab',
    name: 'Dr. Elena Rostova',
    title: 'QA Reviewer',
    roles: ['REVIEWER', 'MICROBIOLOGIST', 'VIEWER'],
  },
  {
    id: 'usr-view-01',
    email: 'viewer@microlims.lab',
    name: 'Dr. James Wilson',
    title: 'Consulting Physician',
    roles: ['VIEWER'],
  },
];

export const MOCK_SAMPLES = [
  {
    id: 'SMP-2026-0081',
    accession_number: 'ACC-881920',
    patient_id: 'PT-994012',
    patient_name: 'Eleanor Vance',
    specimen_type: 'Blood Culture',
    collection_site: 'Right Antebrachial Vein',
    status: 'IN_INCUBATION',
    priority: 'STAT',
    department: 'Microbiology BSL-2',
    collection_date: '2026-08-28T14:30:00Z',
    received_date: '2026-08-28T15:15:00Z',
    technician_name: 'Alex Rivera',
    notes: 'Suspected sepsis post-cholecystectomy. Dual aerobic/anaerobic bottles loaded.',
    barcode: 'BC-881920-BLD',
  },
  {
    id: 'SMP-2026-0082',
    accession_number: 'ACC-881921',
    patient_id: 'PT-442109',
    patient_name: 'Marcus Brody',
    specimen_type: 'Cerebrospinal Fluid (CSF)',
    collection_site: 'L3-L4 Interspace',
    status: 'AST_PENDING',
    priority: 'STAT',
    department: 'Microbiology BSL-3',
    collection_date: '2026-08-28T18:00:00Z',
    received_date: '2026-08-28T18:25:00Z',
    technician_name: 'Alex Rivera',
    notes: 'Severe acute meningitis symptoms. Gram stain showed gram-negative diplococci.',
    barcode: 'BC-881921-CSF',
  },
  {
    id: 'SMP-2026-0083',
    accession_number: 'ACC-881922',
    patient_id: 'PT-551023',
    patient_name: 'Aria Thorne',
    specimen_type: 'Bronchoalveolar Lavage (BAL)',
    collection_site: 'Right Lower Lobe',
    status: 'REVIEW_PENDING',
    priority: 'URGENT',
    department: 'Microbiology BSL-2',
    collection_date: '2026-08-27T09:15:00Z',
    received_date: '2026-08-27T10:00:00Z',
    technician_name: 'Dr. Marcus Vance',
    notes: 'Ventilator-associated pneumonia surveillance. Heavy mucoid colonies observed on MAC.',
    barcode: 'BC-881922-BAL',
  },
  {
    id: 'SMP-2026-0084',
    accession_number: 'ACC-881923',
    patient_id: 'PT-118945',
    patient_name: 'Daniel Hayes',
    specimen_type: 'Synovial Fluid',
    collection_site: 'Left Knee Joint',
    status: 'VERIFIED',
    priority: 'ROUTINE',
    department: 'Microbiology BSL-2',
    collection_date: '2026-08-26T11:00:00Z',
    received_date: '2026-08-26T11:45:00Z',
    technician_name: 'Dr. Marcus Vance',
    notes: 'Joint replacement evaluation. No growth at 72 hours. Final negative verification complete.',
    barcode: 'BC-881923-SYN',
  },
];

export const MOCK_DASHBOARD_METRICS = {
  activeSamples: 148,
  activeSamplesChange: '+12%',
  incubationsInProgress: 42,
  incubationsOverdue: 2,
  astPanelsPending: 18,
  pendingSignOff: 7,
  contaminationRate: '0.42%',
  turnaroundAvgHours: 19.4,
};

export const MOCK_INCUBATIONS = [
  {
    id: 'INC-901',
    sample_id: 'SMP-2026-0081',
    accession_number: 'ACC-881920',
    incubator_id: 'INC-CO2-01',
    temperature: 37.0,
    humidity: 95.0,
    co2_percent: 5.0,
    started_at: '2026-08-28T16:00:00Z',
    target_hours: 48,
    elapsed_hours: 24.5,
    status: 'IN_PROGRESS',
  },
  {
    id: 'INC-902',
    sample_id: 'SMP-2026-0082',
    accession_number: 'ACC-881921',
    incubator_id: 'INC-ANAEROBIC-02',
    temperature: 35.5,
    humidity: 90.0,
    co2_percent: 10.0,
    started_at: '2026-08-28T19:00:00Z',
    target_hours: 24,
    elapsed_hours: 21.5,
    status: 'IN_PROGRESS',
  },
];

export const MOCK_AST_RECORDS = [
  {
    id: 'AST-701',
    sample_id: 'SMP-2026-0082',
    isolate_name: 'Neisseria meningitidis',
    antibiotic: 'Ceftriaxone',
    mic_value: '<= 0.03',
    interpretation: 'SUSCEPTIBLE',
    method: 'Broth Microdilution (E-Test)',
    standard: 'CLSI M100 2026',
  },
  {
    id: 'AST-702',
    sample_id: 'SMP-2026-0082',
    isolate_name: 'Neisseria meningitidis',
    antibiotic: 'Penicillin G',
    mic_value: '0.25',
    interpretation: 'INTERMEDIATE',
    method: 'Broth Microdilution (E-Test)',
    standard: 'CLSI M100 2026',
  },
  {
    id: 'AST-703',
    sample_id: 'SMP-2026-0083',
    isolate_name: 'Klebsiella pneumoniae (ESBL+)',
    antibiotic: 'Meropenem',
    mic_value: '<= 0.25',
    interpretation: 'SUSCEPTIBLE',
    method: 'Automated Vitek-2 Panel',
    standard: 'EUCAST 2026 v14.0',
  },
  {
    id: 'AST-704',
    sample_id: 'SMP-2026-0083',
    isolate_name: 'Klebsiella pneumoniae (ESBL+)',
    antibiotic: 'Ciprofloxacin',
    mic_value: '>= 4.0',
    interpretation: 'RESISTANT',
    method: 'Automated Vitek-2 Panel',
    standard: 'EUCAST 2026 v14.0',
  },
];

export const MOCK_REVIEWS = [
  {
    id: 'REV-501',
    sample_id: 'SMP-2026-0083',
    accession_number: 'ACC-881922',
    submitted_by: 'Dr. Marcus Vance',
    submitted_at: '2026-08-28T17:45:00Z',
    status: 'PENDING_REVIEW',
    priority: 'URGENT',
    preliminary_organism: 'Klebsiella pneumoniae (MDR/ESBL)',
    notes: 'Requires dual QA sign-off for critical ESBL alert broadcast.',
  },
];
